trigger:
- master

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-22.04
    steps:

    - script: docker build -t voltstro/vpbuilder:autobuild -f VoltProjects.Builder/Dockerfile .
      displayName: Build Builder
      workingDirectory: src/

    - script: docker build -t voltstro/vpserver:autobuild -f VoltProjects.Server/Dockerfile .
      displayName: Build Server
      workingDirectory: src/

    - script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      displayName: Docker Login
      env:
        DOCKER_USER: $(DOCKER_USER)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

    - script: docker push voltstro/vpbuilder:autobuild
      displayName: Docker Push Builder

    - script: docker push voltstro/vpserver:autobuild
      displayName: Docker Push Server
