trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-22.04
    steps:
    - task: UseDotNet@2
      displayName: Install .NET 7
      inputs:
        version: 7.x

    - script: dotnet restore src/VoltProjects.sln
      displayName: Restore Packages

    - script: dotnet build src/VoltProjects.sln --no-restore -c $(buildConfiguration)
      displayName: Build Project
